# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cz9x2tpws-capi-aws
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cz9x2tpws-capi-aws
subjects:
- kind: ServiceAccount
  name: cz9x2tpws-capi-aws
  namespace: cz9x2tpws
