# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cz9x2tpws-capi-aws
  namespace: cz9x2tpws
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cz9x2tpws-capi-aws
subjects:
- kind: ServiceAccount
  name: cz9x2tpws-capi-aws
